Repository 30-seconds/30-seconds-web, pull requests merged in 2020-09, with the labels that each got.

#160 Fix footer links
  src/components/molecules/footer/index.jsx
Labels: UI/UX, bug

#163 Fix XMLs injected with data-react-helmet
  gatsby-ssr.js
  src/components/organisms/meta/index.jsx
Labels: SEO, bug

#164 Bump Gatsby to 2.24.53
  package-lock.json
  package.json
Labels: CI/CD, backend, maintenance

#171 Make layout scrollable
  src/components/molecules/cookieConsentPopup/_index.scss
  src/components/molecules/footer/_index.scss
  src/components/molecules/listingAnchors/_index.scss
  src/components/organisms/shell/_index.scss
  src/spec/listing.spec.js
  src/spec/search.spec.js
Labels: UI/UX, enhancement

#168 Add rel attributes to Paginator
  src/components/molecules/paginator/index.jsx
  src/components/molecules/paginator/index.test.jsx
Labels: SEO, enhancement

#169 Add some spacing above static page titles
  src/components/atoms/pageTitle/_index.scss
Labels: UI/UX, enhancement

#167 Development server
  gatsby-node.js
  package-lock.json
  package.json
  src/build/json/index.js
  src/build/snippet/compileSnippet.js
  src/build/snippet/index.js
  src/build/snippet/matchData.js
  src/components/organisms/snippetCard/blogSnippetCard/index.jsx
  src/components/organisms/snippetCard/cssSnippetCard/index.jsx
  src/components/organisms/snippetCard/standardSnippetCard/index.jsx
  src/components/templates/developerPage/index.jsx
  src/components/templates/developerPage/index.scss
  src/config/paths.json
  src/gatsby/createPages.js
  src/gatsby/createPagesStatefully.js
  src/gatsby/index.js
  src/gatsby/onCreateDevServer.js
  src/gatsby/onPreInit.js
  src/lang/en/client/common.js
  src/lang/en/client/developer.js
Labels: CI/CD, backend, enhancement

#172 Update ranker and sorting
  src/build/listing/index.js
  src/build/snippet/compileSnippet.js
  src/build/snippet/snippetData.js
  src/components/molecules/sorter/_index.scss
  src/components/molecules/sorter/index.jsx
  src/components/molecules/sorter/index.test.jsx
  src/components/organisms/snippetList/_index.scss
  src/components/organisms/snippetList/index.jsx
  src/components/organisms/snippetList/index.test.jsx
  src/config/rankingEngine.json
  src/engines/rankingEngine.js
  src/fixtures/requirables.js
  src/fixtures/snippets.js
  src/lang/en/listing/index.js
  src/spec/listing.spec.js
  static/_redirects
Labels: CI/CD, SEO, UI/UX, backend, enhancement

#173 Bump gatsby plugins
  package-lock.json
  package.json
Labels: CI/CD, backend, maintenance

#175 Structured listing data
  src/components/organisms/meta/index.jsx
  src/components/templates/listingPage/index.jsx
  src/components/templates/snippetPage/index.jsx
  src/fixtures/metadata.js
  src/utils/index.js
  src/utils/object.js
  src/utils/object.test.js
Labels: SEO, enhancement

#176 No expertise in cards
  src/build/transformers/transformSnippets.js
  src/build/transformers/transformSnippets.test.js
  src/build/transformers/transformTags.js
  src/components/molecules/previewCard/index.jsx
  src/components/molecules/previewCard/index.test.jsx
  src/config/tags.json
Labels: UI/UX

#184 Post-Q3 cleanup
  gatsby-browser.js
  gatsby-config.js
  package-lock.json
  package.json
  src/build/listing/index.js
  src/build/snippet/parseMarkdown.js
  src/components/atoms/codeBlock/index.jsx
  src/components/organisms/shell/_index.scss
  src/components/organisms/snippetList/index.jsx
  src/styles/_reset.scss
Labels: SEO, UI/UX, enhancement

#188 UX improvements bundle
  src/build/snippet/parseMarkdown.js
  src/components/molecules/footer/_index.scss
  src/components/molecules/paginator/index.jsx
  src/components/organisms/shell/_index.scss
  src/components/organisms/shell/index.jsx
  src/components/organisms/snippetCard/blogSnippetCard/_index.scss
  src/styles/_global_variables.scss
Labels: SEO, UI/UX, bug, enhancement
