Repository 30-seconds/30-seconds-web, pull requests merged in 2021-02, with the labels that each got.

#306 Backend maintenance and search autcomplete
  assets/icons.woff2
  src/blocks/adapters/snippetCollectionChip/index.js
  src/blocks/adapters/snippetCollectionChip/index.test.js
  src/blocks/adapters/snippetPreview/index.js
  src/blocks/entities/collectionConfig/index.js
  src/blocks/entities/collectionConfig/index.test.js
  src/blocks/entities/contentConfig/index.js
  src/blocks/entities/contentConfig/index.test.js
  src/blocks/entities/snippet/index.js
  src/blocks/entities/snippetCollection/index.js
  src/blocks/entities/snippetCollection/index.test.js
  src/blocks/utilities/extractor/index.js
  src/components/atoms/collectionChip/index.jsx
  src/components/atoms/collectionChip/index.test.js
  src/components/organisms/searchResults/index.jsx
  src/components/templates/searchPage/index.jsx
  src/components/templates/settingsPage/index.jsx
  src/fixtures/blocks/contentConfigs.js
  src/fixtures/collections.js
  src/jobs/add_content_source.sh
  src/lang/en/settings/index.js
  src/state/search.js
  src/state/shell.js
  src/typedefs/proptypes/chip.js
Labels: UI/UX, backend, enhancement, maintenance

#310 Remove Redux
  gatsby-browser.js
  gatsby-ssr.js
  package-lock.json
  package.json
  src/components/atoms/button/codepenButton/index.test.jsx
  src/components/atoms/button/copyButton/index.test.jsx
  src/components/hooks/useGtagEvent.js
  src/components/molecules/actions/index.test.jsx
  src/components/molecules/cookieConsentPopup/index.jsx
  src/components/molecules/cookieConsentPopup/index.test.jsx
  src/components/molecules/developmentControls/index.jsx
  src/components/molecules/search/index.jsx
  src/components/molecules/search/index.test.jsx
  src/components/organisms/meta/index.jsx
  src/components/organisms/meta/index.test.jsx
  src/components/organisms/searchResults/index.jsx
  src/components/organisms/searchResults/index.test.jsx
  src/components/organisms/shell/index.jsx
  src/components/organisms/shell/index.test.jsx
  src/components/organisms/snippetCard/blogSnippetCard/index.test.jsx
  src/components/organisms/snippetCard/cssSnippetCard/index.test.jsx
  src/components/organisms/snippetCard/index.test.jsx
  src/components/organisms/snippetCard/standardSnippetCard/index.test.jsx
  src/components/organisms/snippetList/index.test.jsx
  src/components/templates/collectionsPage/index.jsx
  src/components/templates/collectionsPage/index.test.jsx
  src/components/templates/homePage/index.test.jsx
  src/components/templates/listingPage/index.test.jsx
  src/components/templates/notFoundPage/index.test.jsx
  src/components/templates/searchPage/index.jsx
  src/components/templates/searchPage/index.test.jsx
  src/components/templates/settingsPage/index.jsx
  src/components/templates/settingsPage/index.test.jsx
  src/components/templates/snippetPage/index.test.jsx
  src/components/templates/staticPage/index.test.jsx
  src/state/ContextWrapper.jsx
  src/state/ReduxWrapper.jsx
  src/state/createPersistConfig.js
  src/state/index.js
  src/state/navigation.js
  src/state/search.js
  src/state/shell.js
  src/state/utils.js
  src/test/utils.js
Labels: UI/UX, development, maintenance

#312 Cookieless analytics
  gatsby-ssr.js
  src/components/hooks/useGtagEvent.js
  src/components/molecules/_index.scss
  src/components/molecules/cookieConsentPopup/_index.scss
  src/components/molecules/cookieConsentPopup/index.jsx
  src/components/molecules/cookieConsentPopup/index.test.jsx
  src/components/molecules/footer/_index.scss
  src/components/organisms/meta/index.jsx
  src/components/organisms/meta/index.test.jsx
  src/components/organisms/shell/index.jsx
  src/components/organisms/shell/index.test.jsx
  src/components/templates/settingsPage/index.jsx
  src/lang/en/client/cookieConsent.js
  src/lang/en/cookies/theCookiesWeSet.html
  src/lang/en/settings/index.js
  src/settings/global.json
  src/state/shell.js
Labels: SEO, UI/UX

#313 Fix context-related bugs
  src/components/atoms/button/regularButton/_index.scss
  src/components/atoms/card/_index.scss
  src/components/atoms/collectionChip/_index.scss
  src/components/atoms/pageBackdrop/_index.scss
  src/components/atoms/toggle/_index.scss
  src/components/molecules/actions/_index.scss
  src/components/molecules/cookieConsentPopup/index.jsx
  src/components/molecules/listingAnchors/_index.scss
  src/components/molecules/paginator/_index.scss
  src/components/molecules/search/_index.scss
  src/components/molecules/sorter/_index.scss
  src/components/organisms/shell/_index.scss
  src/components/organisms/snippetCard/blogSnippetCard/_index.scss
  src/styles/_anchor.scss
  src/styles/_code.scss
  src/styles/_global_variables.scss
Labels: bug

#314 Prefer excerpt when provided
  src/blocks/entities/snippet/index.js
  src/blocks/entities/snippet/index.test.js
  src/fixtures/blocks/snippets.js
Labels: backend
