Repository 30-seconds/30-seconds-web, pull requests merged in 2021-08, with the labels that each got.

#355 Fix Git snippet example title bug
  src/components/atoms/codeBlock/_index.scss
Labels: bug

#358 Integrate Prettier for SCSS files
  .vscode/settings.json
  src/components/atoms/breadcrumbs/_index.scss
  src/components/atoms/card/_index.scss
  src/components/atoms/codeBlock/_index.scss
  src/components/molecules/actions/_index.scss
  src/components/molecules/cookieConsentPopup/_index.scss
  src/components/molecules/paginator/_index.scss
  src/components/molecules/search/_index.scss
  src/components/organisms/recommendationList/_index.scss
  src/components/organisms/shelf/_index.scss
  src/components/organisms/shell/_index.scss
  src/components/organisms/snippetCard/blogSnippetCard/_index.scss
  src/components/organisms/snippetCard/cssSnippetCard/_index.scss
  src/components/organisms/snippetCard/standardSnippetCard/_index.scss
  src/components/organisms/snippetList/_index.scss
  src/styles/_border-radii.scss
  src/styles/_buttons.scss
  src/styles/_colors.scss
  src/styles/_fonts.scss
  src/styles/_icons.scss
  src/styles/_layout.scss
  src/styles/_reset.scss
  src/styles/_scrollbars.scss
  src/styles/_spacing.scss
  src/styles/_surfaces.scss
  src/styles/type/_anchor.scss
  src/styles/type/_code.scss
  src/styles/type/_colors.scss
  src/styles/type/_font-sizes.scss
  src/styles/type/_font-styles.scss
Labels: development

#360 Upgrade jest and related dependencies
  package-lock.json
  package.json
  src/blocks/serializers/listing/index.test.js
  src/test/jest-config.json
Labels: enhancement, tests, maintenance, dependencies

#361 Backend maintenance
  package.json
  src/blocks/entities/collectionConfig/index.js
  src/blocks/entities/contentConfig/index.js
  src/blocks/entities/contentConfig/index.test.js
  src/blocks/entities/snippet/index.js
  src/blocks/entities/snippet/index.test.js
  src/blocks/entities/snippetCollection/index.js
  src/blocks/parsers/file/index.js
  src/blocks/parsers/json/index.js
  src/blocks/parsers/markdown/index.js
  src/blocks/parsers/markdown/index.test.js
  src/blocks/parsers/text/index.js
  src/blocks/serializers/asset/index.js
  src/blocks/serializers/chirp/index.js
  src/blocks/serializers/feed/index.js
  src/blocks/serializers/hub/index.js
  src/blocks/serializers/icon/index.js
  src/blocks/serializers/json/index.js
  src/blocks/serializers/listing/index.js
  src/blocks/serializers/manifest/index.js
  src/blocks/serializers/sitemap/index.js
  src/blocks/serializers/snippet/index.js
  src/blocks/utilities/chunk/index.js
  src/blocks/utilities/content/index.js
  src/blocks/utilities/env/index.js
  src/blocks/utilities/env/index.test.js
  src/blocks/utilities/extractor/index.js
  src/blocks/utilities/instanceCache/index.js
  src/blocks/utilities/instanceCache/index.test.js
  src/blocks/utilities/logger/index.js
  src/blocks/utilities/logger/index.test.js
  src/blocks/utilities/ranker/index.js
  src/blocks/utilities/recommender/index.js
  src/blocks/utilities/requirements/index.js
  src/blocks/utilities/screenshot/index.js
  src/blocks/utilities/tag/index.js
  src/blocks/utilities/twitterBot/index.js
  src/scripts/build.js
  src/scripts/console.js
  src/scripts/create.js
  src/scripts/develop.js
  src/scripts/tweet.js
  src/styles/_icons.scss
  src/utils/search.js
Labels: backend, maintenance
