Repository 30-seconds/30-seconds-web, pull requests merged in 2021-01, with the labels that each got.

#252 Twitter bot
  .github/workflows/tweet.yml
  .gitignore
  package-lock.json
  package.json
  src/blocks/serializers/chirp/index.js
  src/blocks/utilities/screenshot/index.js
  src/blocks/utilities/twitterBot/index.js
  src/gatsby/onPostBuild.js
  src/scripts/build.js
  src/scripts/tweet.js
  src/settings/chirp.json
  src/settings/paths.json
  src/settings/tweet.json
  src/utils/array.js
  src/utils/array.test.js
  src/utils/index.js
  src/utils/string.js
  src/utils/string.test.js
Labels: CI/CD, backend, development, enhancement, experiment, maintenance

#265 Frontend optimizations
  package-lock.json
  package.json
  src/blocks/parsers/markdown/index.js
  src/components/atoms/card/_mixins.scss
  src/components/molecules/_index.scss
  src/components/molecules/developmentControls/index.jsx
  src/components/molecules/developmentControls/index.scss
  src/components/molecules/previewCard/index.jsx
  src/components/molecules/previewCard/index.test.jsx
  src/components/molecules/simpleCard/index.jsx
  src/components/organisms/shell/index.jsx
  src/components/organisms/snippetCard/blogSnippetCard/_index.scss
  src/components/organisms/snippetCard/blogSnippetCard/index.jsx
  src/components/templates/listingPage/index.jsx
  src/lang/en/client/common.js
  src/lang/en/client/developer.js
  src/templates/rssTemplate.hbs
Labels: SEO, UI/UX, bug, enhancement, maintenance

#267 Update build code
  src/blocks/entities/contentConfig/index.js
  src/blocks/entities/contentConfig/index.test.js
  src/blocks/serializers/chirp/index.js
  src/blocks/utilities/path/index.js
  src/blocks/utilities/path/index.test.js
  src/gatsby/createPagesStatefully.js
  src/templates/rssTemplate.hbs
Labels: CI/CD, SEO, backend

#268 Fix image in structured data
  src/utils/object.js
Labels: SEO, bug

#277 SEO/UI improvements
  src/components/atoms/card/_index.scss
  src/components/atoms/pageTitle/_index.scss
  src/components/molecules/previewCard/_index.scss
  src/components/organisms/meta/index.jsx
  src/components/organisms/meta/index.test.jsx
  src/components/organisms/snippetCard/blogSnippetCard/_index.scss
  src/components/organisms/snippetList/_index.scss
  static/_redirects
Labels: SEO, UI/UX

#282 Twitter bot updates
  .github/workflows/tweet.yml
  src/blocks/serializers/chirp/index.js
  src/blocks/utilities/screenshot/index.js
Labels: SEO, enhancement, experiment, maintenance

#285 Twitter experiment
  src/blocks/utilities/screenshot/index.js
  src/settings/chirp.json
Labels: SEO, enhancement, experiment

#292 Deprecate CTA
  src/components/molecules/_index.scss
  src/components/molecules/cta/_index.scss
  src/components/molecules/cta/index.jsx
  src/components/molecules/cta/index.test.jsx
  src/components/organisms/snippetList/index.jsx
  src/components/organisms/snippetList/index.test.jsx
  src/components/templates/snippetPage/index.jsx
  src/lang/en/client/cta.js
Labels: SEO, maintenance

#298 Collection images
  src/blocks/adapters/snippetCollectionListing/index.js
  src/blocks/entities/snippetCollection/index.js
  src/blocks/serializers/asset/index.js
  src/components/molecules/listingAnchors/_index.scss
  src/components/organisms/snippetList/_index.scss
  src/components/organisms/snippetList/index.jsx
  src/components/templates/listingPage/index.jsx
  src/settings/paths.json
Labels: UI/UX, backend, enhancement
