Repository 30-seconds/30-seconds-web, pull requests merged in 2022-01, with the labels that each got.

#386 Update footer
  src/lang/en/client/footer.js
Labels: maintenance

#387 Add from param to internal links
  src/components/atoms/breadcrumbs/index.jsx
  src/components/atoms/collectionChip/index.jsx
  src/components/atoms/collectionChip/index.test.js
  src/components/atoms/listingAnchors/index.jsx
  src/components/molecules/paginator/index.jsx
  src/components/molecules/previewCard/index.jsx
  src/components/molecules/search/index.jsx
  src/components/organisms/previewCardList/index.jsx
  src/components/organisms/recommendationList/index.jsx
  src/components/organisms/shelf/index.jsx
Labels: enhancement, UI/UX, SEO

#390 Cosmos design system polish up
  src/components/atoms/card/index.jsx
  src/components/atoms/pageTitle/_index.scss
  src/components/molecules/cookieConsentPopup/index.jsx
  src/components/molecules/previewCard/index.jsx
  src/components/molecules/search/index.jsx
  src/scripts/develop.js
  src/styles/_expertise.scss
  src/styles/_surfaces.scss
  src/styles/type/_colors.scss
Labels: enhancement, UI/UX

#391 Revamp hub pages
  public/_redirects
  src/blocks/application.js
  src/blocks/extractor/index.js
  src/blocks/models/listing.js
  src/blocks/models/page.js
  src/blocks/schema.js
  src/blocks/schema.test.js
  src/blocks/writers/pageWriter.js
  src/lang/en/shared/index.js
  src/pages/collections.jsx
  src/styles/_buttons.scss
  src/test/fixtures/content.js
Labels: enhancement, UI/UX, backend, SEO

#393 Stop using prop-types
  .eslintrc.json
  package.json
  src/components/atoms/breadcrumbs/index.jsx
  src/components/atoms/card/index.jsx
  src/components/atoms/codeBlock/index.jsx
  src/components/atoms/collectionChip/index.jsx
  src/components/atoms/image/index.jsx
  src/components/atoms/listingAnchors/index.jsx
  src/components/atoms/pageTitle/index.jsx
  src/components/molecules/actions/index.jsx
  src/components/molecules/cookieConsentPopup/index.jsx
  src/components/molecules/pageBackdrop/index.jsx
  src/components/molecules/paginator/index.jsx
  src/components/molecules/previewCard/index.jsx
  src/components/molecules/search/index.jsx
  src/components/organisms/meta/index.jsx
  src/components/organisms/previewCardList/index.jsx
  src/components/organisms/recommendationList/index.jsx
  src/components/organisms/searchResults/index.jsx
  src/components/organisms/shelf/index.jsx
  src/components/organisms/shell/index.jsx
  src/components/organisms/snippetCard/blogSnippetCard/index.jsx
  src/components/organisms/snippetCard/cssSnippetCard/index.jsx
  src/components/organisms/snippetCard/standardSnippetCard/index.jsx
  src/components/templates/homePage/index.jsx
  src/components/templates/listingPage/index.jsx
  src/components/templates/notFoundPage/index.jsx
  src/components/templates/searchPage/index.jsx
  src/components/templates/snippetPage/index.jsx
  src/components/templates/staticPage/index.jsx
  src/pages/_app.jsx
  src/state/utils.js
  src/test/utils.js
  src/typedefs/proptypes/authors.js
  src/typedefs/proptypes/chip.js
  src/typedefs/proptypes/code.js
  src/typedefs/proptypes/html.js
  src/typedefs/proptypes/index.js
  src/typedefs/proptypes/language.js
  src/typedefs/proptypes/meta.js
  src/typedefs/proptypes/paginator.js
  src/typedefs/proptypes/snippet.js
  src/typedefs/proptypes/tags.js
Labels: enhancement, UI/UX, maintenance, development, dependencies

#395 Data optimizations
  src/blocks/extractor/index.js
  src/blocks/models/page.js
  src/blocks/models/snippet.js
  src/blocks/schema.test.js
  src/blocks/serializers/snippetContextSerializer.js
  src/blocks/utilities/schemer.js
  src/blocks/utilities/schemer.test.js
  src/components/atoms/_index.scss
  src/components/atoms/codeBlock/_index.scss
  src/components/atoms/codeBlock/index.jsx
  src/components/atoms/codeBlock/index.test.jsx
  src/components/organisms/meta/index.jsx
  src/components/organisms/meta/index.test.jsx
  src/components/organisms/snippetCard/_index.scss
  src/components/organisms/snippetCard/blogSnippetCard/index.jsx
  src/components/organisms/snippetCard/blogSnippetCard/index.test.jsx
  src/components/organisms/snippetCard/cssSnippetCard/_index.scss
  src/components/organisms/snippetCard/cssSnippetCard/index.jsx
  src/components/organisms/snippetCard/cssSnippetCard/index.test.jsx
  src/components/organisms/snippetCard/index.jsx
  src/components/organisms/snippetCard/index.test.jsx
  src/components/organisms/snippetCard/standardSnippetCard/_index.scss
  src/components/organisms/snippetCard/standardSnippetCard/index.jsx
  src/components/organisms/snippetCard/standardSnippetCard/index.test.jsx
  src/components/templates/homePage/index.jsx
  src/components/templates/listingPage/index.jsx
  src/components/templates/snippetPage/index.jsx
  src/lang/en/shared/index.js
  src/styles/type/_code.scss
  src/test/fixtures/factories/snippet.js
  src/utils/index.js
  src/utils/object.js
  src/utils/object.test.js
Labels: enhancement, tests, UI/UX, backend, maintenance, development
