Repository 30-seconds/30-seconds-web, pull requests merged in 2022-02, with the labels that each got.

#396 Data optimizations 2
  assets/icons.woff2
  src/blocks/extractor/index.js
  src/blocks/models/page.js
  src/blocks/models/snippet.js
  src/blocks/schema.test.js
  src/blocks/serializers/listingContextSerializer.js
  src/blocks/serializers/listingPreviewSerializer.js
  src/blocks/serializers/snippetContextSerializer.js
  src/blocks/serializers/snippetPreviewSerializer.js
  src/components/atoms/breadcrumbs/index.jsx
  src/components/atoms/card/index.jsx
  src/components/atoms/collectionChip/index.jsx
  src/components/atoms/collectionChip/index.test.js
  src/components/atoms/listingAnchors/index.jsx
  src/components/atoms/pageTitle/_index.scss
  src/components/molecules/actions/index.jsx
  src/components/molecules/paginator/index.jsx
  src/components/molecules/previewCard/index.jsx
  src/components/molecules/previewCard/index.test.jsx
  src/components/molecules/search/index.jsx
  src/components/organisms/_index.scss
  src/components/organisms/meta/index.jsx
  src/components/organisms/previewCardList/index.jsx
  src/components/organisms/recommendationList/_index.scss
  src/components/organisms/recommendationList/index.jsx
  src/components/organisms/recommendationList/index.test.jsx
  src/components/organisms/searchResults/index.jsx
  src/components/organisms/searchResults/index.test.jsx
  src/components/organisms/shelf/index.jsx
  src/components/organisms/snippetCard/blogSnippetCard/index.jsx
  src/components/organisms/snippetCard/blogSnippetCard/index.test.jsx
  src/components/organisms/snippetCard/standardSnippetCard/index.jsx
  src/components/organisms/snippetCard/standardSnippetCard/index.test.jsx
  src/components/templates/listingPage/_index.scss
  src/components/templates/listingPage/index.jsx
  src/components/templates/listingPage/index.test.jsx
  src/components/templates/notFoundPage/index.jsx
  src/components/templates/searchPage/index.jsx
  src/components/templates/searchPage/index.test.jsx
  src/components/templates/snippetPage/index.jsx
  src/components/templates/snippetPage/index.test.jsx
  src/icons/share.svg
  src/lang/en/client/common.js
  src/lang/en/client/search.js
  src/lang/en/shared/index.js
  src/styles/_icons.scss
  src/test/fixtures/content.js
  src/test/fixtures/factories/snippet.js
Labels: enhancement, UI/UX, backend, maintenance, SEO, development

#398 Remove special handling for blog snippet cards
  src/blocks/extractor/index.js
  src/blocks/extractor/markdownParser.js
  src/blocks/extractor/markdownParser.test.js
  src/blocks/models/page.js
  src/blocks/models/repository.js
  src/blocks/models/snippet.js
  src/blocks/schema.test.js
  src/components/atoms/card/_index.scss
  src/components/atoms/card/index.jsx
  src/components/organisms/snippetCard/_index.scss
  src/components/organisms/snippetCard/blogSnippetCard/index.jsx
  src/components/organisms/snippetCard/blogSnippetCard/index.test.jsx
  src/components/organisms/snippetCard/index.jsx
  src/components/organisms/snippetCard/index.test.jsx
  src/components/organisms/snippetCard/standardSnippetCard/_index.scss
  src/components/organisms/snippetCard/standardSnippetCard/index.jsx
  src/components/organisms/snippetCard/standardSnippetCard/index.test.jsx
  src/components/templates/snippetPage/index.jsx
  src/components/templates/snippetPage/index.test.jsx
  src/styles/type/_code.scss
  src/test/fixtures/content.js
Labels: enhancement, UI/UX, backend, maintenance, SEO, design

#399 Mobile enhancements
  src/components/atoms/footer/index.jsx
  src/components/molecules/search/_index.scss
  src/components/molecules/search/index.jsx
  src/components/organisms/shelf/_index.scss
  src/components/organisms/shell/_index.scss
Labels: enhancement, UI/UX, maintenance, design

#401 Mobile enhancements (2)
  src/blocks/extractor/markdownParser.js
  src/components/atoms/card/index.jsx
  src/styles/_reset.scss
Labels: enhancement, UI/UX, maintenance, design

#402 Tidy up CSS
  src/blocks/extractor/markdownParser.js
  src/components/atoms/card/_index.scss
  src/components/atoms/card/index.jsx
  src/components/molecules/previewCard/index.jsx
  src/components/molecules/previewCard/index.test.jsx
  src/components/organisms/shell/_index.scss
  src/components/organisms/shell/index.jsx
  src/components/organisms/snippetCard/index.jsx
  src/components/organisms/snippetCard/index.test.jsx
Labels: UI/UX, maintenance

#403 Title update
  src/blocks/models/snippet.js
  src/blocks/schema.test.js
  src/blocks/utilities/recommender.js
  src/components/atoms/card/_index.scss
Labels: enhancement, backend, maintenance

#405 Remove tagIcons field from Language
  src/blocks/extractor/index.js
  src/blocks/models/language.js
  src/blocks/models/snippet.js
  src/test/fixtures/content.js
Labels: enhancement, backend, maintenance

#406 Flatten object types in models
  src/blocks/application.js
  src/blocks/extractor/index.js
  src/blocks/extractor/markdownParser.js
  src/blocks/extractor/markdownParser.test.js
  src/blocks/models/listing.js
  src/blocks/models/page.js
  src/blocks/models/repository.js
  src/blocks/models/snippet.js
  src/blocks/serializers/snippetContextSerializer.js
  src/blocks/serializers/snippetPreviewSerializer.js
  src/blocks/utilities/ranker.js
  src/blocks/writers/assetWriter.js
  src/test/fixtures/content.js
Labels: backend, maintenance
